//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceClient.FinanceServiceRef {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://localhost:44324/FinanceWebService.asmx", ConfigurationName="FinanceServiceRef.FinanceWebServiceSoap")]
    public interface FinanceWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Register(string fullname, string email, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RegisterAsync(string fullname, string email, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string email, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginAsync(string email, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/AddRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddRecord(string desc, int amount, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/AddRecord", ReplyAction="*")]
        System.Threading.Tasks.Task AddRecordAsync(string desc, int amount, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/DeleteRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteRecord(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/DeleteRecord", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteRecordAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/UpdateRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateRecord(int id, string desc, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/UpdateRecord", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateRecordAsync(int id, string desc, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/GetAllRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllRecords(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44324/FinanceWebService.asmx/GetAllRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllRecordsAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinanceWebServiceSoapChannel : FinanceClient.FinanceServiceRef.FinanceWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanceWebServiceSoapClient : System.ServiceModel.ClientBase<FinanceClient.FinanceServiceRef.FinanceWebServiceSoap>, FinanceClient.FinanceServiceRef.FinanceWebServiceSoap {
        
        public FinanceWebServiceSoapClient() {
        }
        
        public FinanceWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanceWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string Register(string fullname, string email, string pwd) {
            return base.Channel.Register(fullname, email, pwd);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string fullname, string email, string pwd) {
            return base.Channel.RegisterAsync(fullname, email, pwd);
        }
        
        public string Login(string email, string pwd) {
            return base.Channel.Login(email, pwd);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string email, string pwd) {
            return base.Channel.LoginAsync(email, pwd);
        }
        
        public void AddRecord(string desc, int amount, string email) {
            base.Channel.AddRecord(desc, amount, email);
        }
        
        public System.Threading.Tasks.Task AddRecordAsync(string desc, int amount, string email) {
            return base.Channel.AddRecordAsync(desc, amount, email);
        }
        
        public void DeleteRecord(int id) {
            base.Channel.DeleteRecord(id);
        }
        
        public System.Threading.Tasks.Task DeleteRecordAsync(int id) {
            return base.Channel.DeleteRecordAsync(id);
        }
        
        public void UpdateRecord(int id, string desc, int amount) {
            base.Channel.UpdateRecord(id, desc, amount);
        }
        
        public System.Threading.Tasks.Task UpdateRecordAsync(int id, string desc, int amount) {
            return base.Channel.UpdateRecordAsync(id, desc, amount);
        }
        
        public System.Data.DataTable GetAllRecords(string email) {
            return base.Channel.GetAllRecords(email);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllRecordsAsync(string email) {
            return base.Channel.GetAllRecordsAsync(email);
        }
    }
}
